pull request
Wzeun/MyProject pull request #1
Opened 2022-12-15 09:54 UTC by Wzeun

2022-12-16 14:40 UTC, crezul requested changes
Поздоровляю з першою задачею
Як і все що ми робимо вперше в житті - воно не ідеальне
Я добавив декілька коментів, на які потрібно звернути уваги
Дякую за скрін роботи програми

Якщо з чимось не згоден, то залиш свою аргументовану відповідь під моїм коментом
Якщо згоден - то також залиш комент типу Ок. Згоден. Зроблю. Зроблю так і так чи щось подібне

Далі потрібно закомітити ченжі згідно ревью з текстом коміту "Changes after review were added"
і знову я буду проводити ревью

Ревю відбувається доти,  поки у ревювера(тобто у мене) не буде зауважень
Далі після мого апрува можеш мержити код в мастер

2022-12-16 14:40 UTC, crezul commented on NewYear/MyProject/MyProject/MyProject.csproj.user
> +<?xml version="1.0" encoding="utf-8"?>
цей файл генерується на твоїй машині і не повинен бути в репозиторії
Також до таких файлів відносяться файли компіляції, obj файли

2022-12-16 14:40 UTC, crezul commented on NewYear/MyProject/MyProject/Program.cs
> +            Console.WriteLine("Введите дату:");
не потрібно змішувати кацапську мову з українською
Давай в майбутньому використовувати одну мову: англійську чи українську

2022-12-16 14:40 UTC, crezul commented on NewYear/MyProject/MyProject/Program.cs
> +            int DayConvertToInt = Convert.ToInt32(Day);
а що буде якщо ввести якийсь символ,  тобто не число?
Гадаю що потрібно обробити ексепшин який генерується при спробі сконвертити букву в число

2022-12-16 14:40 UTC, crezul commented on NewYear/MyProject/MyProject/Program.cs
> +            if (Convert.ToInt32(Day) > 31)
тут є декілька проблем:
 - юзер ввів не число
 - юзер ввів число меньше 1
 - не кожен місяць має 31 день

2022-12-16 14:40 UTC, crezul commented on NewYear/MyProject/MyProject/Program.cs
> +            if (Convert.ToInt32(Day) > 31)
потрібно перевірити всі ці кейси

2022-12-16 14:40 UTC, crezul commented on NewYear/MyProject/MyProject/Program.cs
> +            //else { //Environment.Exit(ExitCode); }
ми не залишаємо закоментованого кода
в цьому немає ніякого сенсу і користі

2022-12-16 14:40 UTC, crezul commented on NewYear/MyProject/MyProject/Program.cs
> +            //int MonthConvertToInt = Convert.ToInt32(Month);
закоментований код потрібно видалити

2022-12-16 14:40 UTC, crezul commented on NewYear/MyProject/MyProject/Program.cs
> +                Console.WriteLine("Введено некоректний місяць");
помилка

2022-12-16 14:40 UTC, crezul commented on NewYear/MyProject/MyProject/Program.cs
> +            if (Month == "Січень") { FinallyMonth = FinallyMonth + 1; }
подивись в бік використання словника
щоб можна було задати місяць і кількість днів 
щось типу такого

`{"January":31, "February":28, "March":31,....`

2022-12-16 14:40 UTC, crezul commented on NewYear/MyProject/MyProject/Program.cs
> +            if (Month == "Січень") { FinallyMonth = FinallyMonth + 1; }
словник - https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=net-7.0 - 
має багато переваг: швидкий пошук, зручно апдейтити,  багато допоміжних фукнції для роботи з елеметами

2022-12-16 15:24 UTC, Wzeun commented on NewYear/MyProject/MyProject/Program.cs
> +            Console.WriteLine("Введите дату:");
Добре зрозумів)

2022-12-16 15:45 UTC, Wzeun commented on NewYear/MyProject/MyProject/Program.cs
> +            //else { //Environment.Exit(ExitCode); }
Я просто перевіряв як программа працює з ними і без них

2022-12-16 16:13 UTC, Wzeun commented on NewYear/MyProject/MyProject/Program.cs
> +                Console.WriteLine("Введено некоректний місяць");
Помилка в коді чи граматична?

2022-12-19 12:16 UTC, crezul commented on NewYear/MyProject/MyProject/Program.cs
> +                Console.WriteLine("Введено некоректний місяць");
щось не бачу тут помилки
Мабудь я помилився

2022-12-26 10:31 UTC, closed without merging